[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
uuid = { version = "1.6.1", features = ["v4"] }
futures = { version = "0.3.29", features = [] }
tokio = "1.35.0"
tokio-tungstenite = { version = "0.21.0", features = [] }
tungstenite = { version = "0.21.0", features = [] }
url = { version = "2.5.0", features = [] }
actix = "0.13.1"
time = "0.3.30"
serde = "1.0.193"
serde_json = "1.0.108"
anyhow = "1.0.75"
term = { version = "0.7.0", features = [] }
clap = { version = "4.4.11", features = ["derive"] }