[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
uuid = { version = "1.6.1", features = ["v4"] }
rodio = "0.17.3"
actix = "0.13.1"
tokio = { version = "1", features = ["full"] }
actix-rt = "2.9.0"
anyhow = "1.0.75"
