workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
    image: rust:latest-alpine
    tags:
    - shared-fi
    before_script:
        - apk add alsa-lib-dev


stages:
    - build
    - test

build:
    stage: build
    script:
        - cargo build --verbose

lint:
    stage: test
    script:
        - rustup component add rustfmt
        - cargo fmt -- --check
        - rustup component add clippy
        - cargo clippy -- -D warnings

test:
    stage: test
    script:
        - cargo test --verbose
